import 'dart:typed_data';

import 'package:flutter/services.dart' show rootBundle;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

/// One row of a GST export — a single payment against a subscription,
/// GST-inclusive (matches how the amount is actually charged/paid).
class GstLineItem {
  const GstLineItem({
    required this.serviceName,
    required this.vendorLabel,
    required this.amountPaid,
  });

  final String serviceName;
  final String vendorLabel;
  final double amountPaid;

  static const gstRate = 0.18;

  double get exTaxAmount => amountPaid / (1 + gstRate);
  double get gstAmount => amountPaid - exTaxAmount;
}

class ExportService {
  ExportService._();

  static String _money(double v) => '₹${v.toStringAsFixed(2)}';

  /// Base14 PDF fonts (Helvetica etc.) don't include the ₹ glyph (added to
  /// Unicode in 2010, after those font encodings were fixed) — embed DM Sans,
  /// which does, rather than silently rendering a missing-glyph box.
  static Future<pw.ThemeData> _pdfTheme() async {
    final regularData = await rootBundle.load('assets/fonts/DMSans-Regular.ttf');
    final boldData = await rootBundle.load('assets/fonts/DMSans-Bold.ttf');
    return pw.ThemeData.withFont(
      base: pw.Font.ttf(regularData),
      bold: pw.Font.ttf(boldData),
    );
  }

  static Future<Uint8List> generatePdf({
    required String entityName,
    String? gstin,
    required String periodLabel,
    required List<GstLineItem> items,
  }) async {
    final doc = pw.Document(theme: await _pdfTheme());
    final totalExTax = items.fold<double>(0, (sum, i) => sum + i.exTaxAmount);
    final totalGst = items.fold<double>(0, (sum, i) => sum + i.gstAmount);
    final totalAmount = items.fold<double>(0, (sum, i) => sum + i.amountPaid);

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'SubTrakr — GST Report',
                style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold),
              ),
              pw.SizedBox(height: 12),
              pw.Text('Company: $entityName'),
              if (gstin != null && gstin.isNotEmpty) pw.Text('GSTIN: $gstin'),
              pw.Text('Period: $periodLabel'),
              pw.SizedBox(height: 16),
              pw.Table(
                border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.5),
                columnWidths: const {
                  0: pw.FlexColumnWidth(3),
                  1: pw.FlexColumnWidth(2.2),
                  2: pw.FlexColumnWidth(1.8),
                  3: pw.FlexColumnWidth(1.6),
                  4: pw.FlexColumnWidth(1.8),
                },
                children: [
                  pw.TableRow(
                    decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                    children: [
                      _cell('Service', bold: true),
                      _cell('Vendor', bold: true),
                      _cell('Amount', bold: true),
                      _cell('GST @18%', bold: true),
                      _cell('Total', bold: true),
                    ],
                  ),
                  for (final item in items)
                    pw.TableRow(
                      children: [
                        _cell(item.serviceName),
                        _cell(item.vendorLabel),
                        _cell(_money(item.exTaxAmount)),
                        _cell(_money(item.gstAmount)),
                        _cell(_money(item.amountPaid)),
                      ],
                    ),
                  pw.TableRow(
                    decoration: const pw.BoxDecoration(color: PdfColors.grey100),
                    children: [
                      _cell('TOTAL', bold: true),
                      _cell(''),
                      _cell(_money(totalExTax), bold: true),
                      _cell(_money(totalGst), bold: true),
                      _cell(_money(totalAmount), bold: true),
                    ],
                  ),
                ],
              ),
              pw.SizedBox(height: 24),
              pw.Text(
                'Generated by SubTrakr · subtrakr.me',
                style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
              ),
            ],
          );
        },
      ),
    );
    return doc.save();
  }

  static pw.Widget _cell(String text, {bool bold = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(
        text,
        style: pw.TextStyle(fontSize: 9, fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal),
      ),
    );
  }

  static String generateCsv({
    required String entityName,
    String? gstin,
    required String periodLabel,
    required List<GstLineItem> items,
  }) {
    final buffer = StringBuffer();
    buffer.writeln('SubTrakr GST Report');
    buffer.writeln('Company,$entityName');
    if (gstin != null && gstin.isNotEmpty) buffer.writeln('GSTIN,$gstin');
    buffer.writeln('Period,$periodLabel');
    buffer.writeln();
    buffer.writeln('Service,Vendor,Amount,GST @18%,Total');
    for (final item in items) {
      buffer.writeln(
        '${_csvEscape(item.serviceName)},${_csvEscape(item.vendorLabel)},'
        '${item.exTaxAmount.toStringAsFixed(2)},${item.gstAmount.toStringAsFixed(2)},'
        '${item.amountPaid.toStringAsFixed(2)}',
      );
    }
    final totalExTax = items.fold<double>(0, (sum, i) => sum + i.exTaxAmount);
    final totalGst = items.fold<double>(0, (sum, i) => sum + i.gstAmount);
    final totalAmount = items.fold<double>(0, (sum, i) => sum + i.amountPaid);
    buffer.writeln(
      'TOTAL,,${totalExTax.toStringAsFixed(2)},${totalGst.toStringAsFixed(2)},${totalAmount.toStringAsFixed(2)}',
    );
    return buffer.toString();
  }

  static String _csvEscape(String value) {
    if (value.contains(',') || value.contains('"')) {
      return '"${value.replaceAll('"', '""')}"';
    }
    return value;
  }

  static Future<void> shareBytes({
    required Uint8List bytes,
    required String fileName,
    required String mimeType,
  }) async {
    await SharePlus.instance.share(
      ShareParams(
        files: [XFile.fromData(bytes, name: fileName, mimeType: mimeType)],
        fileNameOverrides: [fileName],
      ),
    );
  }
}
